---


- name: apache proxy
  apache2_module:
    name: proxy
  become: True

- name: apache proxy_http
  apache2_module:
    name: proxy_http
  become: True

- name: apache proxy_ajp
  apache2_module:
    name: proxy_ajp
  become: True

- name: apache rewrite
  apache2_module:
    name: rewrite
  become: True

- name: apache deflate
  apache2_module:
    name: deflate
  become: True

- name: apache headers
  apache2_module:
    name: headers
  become: True

- name: apache proxy_balancer
  apache2_module:
    name: proxy_balancer
  become: True

- name: apache proxy_connect
  apache2_module:
    name: proxy_connect
  become: True

- name: apache ssl
  apache2_module:
    name: ssl
  become: True

- name: apache proxy_html
  apache2_module:
    name: proxy_html
  become: True
  notify:
    - restart apache

- name: proxy pass apache configuration
  template:  src=clients_redirection.j2 dest=/etc/apache2/client_redirection
  become: True

- name: hostfile
  template: src=hosts.j2 dest=/etc/hosts
  become: True
  notify:
    - restart apache

- name: reverse proxy apache configuration
  template:
    src: reverse_proxy_apache.conf.j2
    dest: "/etc/apache2/sites-enabled/000-default.conf"
    owner: root
  become: True
  notify:
    - reload apache
