---

- name: Ensure apt-transport-https is installed.
  apt: name=apt-transport-https state=present

- name: Add Nodesource apt key.
  apt_key:
    url: "https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280"
    id: "68576280"
    state: present

- name: Add NodeSource repositories for Node.js.
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"

- name: install php7 and nodejs packages
  apt:
    name: "{{ item }}"
    update_cache: True
  with_items:
    - apache2
    - git
    - libapache2-mod-php
    - mariadb-server
    - php
    - php-cli
    - php-mbstring
    - php-xml
    - php-mysql
    - php-zip
    - php-mcrypt
    - php-intl
    - php-imagick
    - nodejs
    - python-mysqldb
    - gettext
    - jq

- name: apache ssl
  apache2_module:
    name: ssl
  notify:
    - restart apache

- name: Create monarch user
  user:
    name: "{{ monarch_user }}"
    group: "www-data"

- name: monarc directory
  file:
    path: /var/lib/monarc
    state: directory
    owner: "{{ monarch_user }}"
    mode: 0755

- name: install grunt
  command: npm install -g grunt grunt-cli creates=/usr/local/bin/grunt

