---


- name: apache ssl
  apache2_module:
    name: ssl
  become: True
  notify:
    - restart apache

- name: monarc directory
  file:
    path: /var/lib/monarc
    state: directory
    owner: "{{ ansible_user }}"
    mode: 0755
  become: True

- name: install grunt
  command: npm install -g grunt-cli creates=/usr/local/bin/grunt
  become: True

- name: create symlink to /usr/bin/node
  file:
    src: /usr/bin/nodejs
    dest: /usr/bin/node
    state: link
  become: True
